### PR TITLE
Added unicode validations

### PR DESCRIPTION
**Pull request by Krusen**
Added the following:
- IsMultibyte (#15)
- IsHalfWidth (#17)
- IsFullWidth (#16)
- IsVariableWidth (#18)
- IsSurrogatePair (#19)

### CODE REVIEW

**Comment by ByteBlast** [comment]
Many thanks for your contributions, @Krusen. *Really* good work.

Although I am familiar with the purpose of each function, I haven't a clue where the Unicode ranges in some patterns are coming from _yet_. If you know, please teach me. I do not feel comfortable including code that I do not completely understand.

I will take some time to learn the patterns today. Thank you again @Krusen, I am *super* excited to include your changes.

**Comment by Krusen** [comment]
Well, I don't fully understand them all either. To start with I have just copied them directly from validator.js, then they might be optimized later on.

`IsMultibyte` basically just checks if there are any bytes above 127 (0x7F in hex). ASCII goes from 0-127 (7 bits). Extended ASCII (several variations, most used is probably ISO 8859-1, also known as Latin-1) goes from 0-255 (8 bits, single byte) would be considered multibyte with this method even though it isn't, but I don't see how we can handle this case without explicitly using an encoding.
http://www.ascii-code.com/

The others I didn't now about before, but looking at wikipedia they seem to be correct.
- Surrogate pairs: http://en.wikipedia.org/wiki/UTF-16
- Half width and full width: http://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

`IsAfter` and `IsBefore` wasn't actually meant to be included in this pull request, but I'm new to this :smiley: I might have a few changes/additions to those two.

**Comment by ByteBlast** [comment]
I managed to ascertain the purpose the `IsMultiByte` pattern but thank you for your description. I had not though about the implications of Extended ASCII.

I also understand the `IsSurrogatePair` pattern. In essence, surrogates are comprised in two parts:  a high surrogate (in the range 0xD800 to 0xDBFF) followed by a low surrogate (in the range 0xDC00 to 0xDFFF).

All I want to do now is understand the half and full width functions!

**Comment by ByteBlast** [comment]
I am actually pretty happy to merge this pull request now. 

Do you want me to merge now or would you like to make you amendments to `IsAfter` and `IsBefore` first? 

Or would you like to make those amendments in a separate pull request later on?

**Comment by Krusen** [comment]
You can just merge it now. I will make another pull request if it decide to make any changes/additions.

**Comment by ByteBlast** [comment]
Woohoo! Merged :smile: 

Many thanks for your contribution, @Krusen. I really appreciate it.

**Pull request merged**
