### PR TITLE
Added IsNull

### PR DESCRIPTION
**Pull request by PrasadHonrao**
Added Validator.IsNull function and respective unit tests.

### CODE REVIEW

**Comment by ByteBlast** [comment]
Thank you very much for your contributions @PrasadHonrao. I have made some comments for now but no matter what I will include these changes in the code base. :smile_cat:

**Comment by PrasadHonrao** [comment]
I shouldn't have committed Validator project with xunit reference. I did that on my local machine by mistake. Glad to know that you have corrected it. I will implement few more function on this project.

**Comment by ByteBlast** [comment]
I am yet to merge these changes.

I will tweak your code and do that now.

**Comment by ByteBlast** [comment]
Done!

**Pull request closed without merging**
